stages:
  - test
  - build
  - deploy_ift
  - deploy_prom
  - logs

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: unix:///var/run/docker.sock
  WORK_TAG: ""

include:
  - local: '.gitlab/ift_vars.yml'
  - local: '.gitlab/prom_vars.yml'
  - local: '.gitlab/lint.yml'
  - local: '.gitlab/build.yml'
  - local: '.gitlab/deploy.yml'
  - local: '.gitlab/healthcheck.yml'
  - local: '.gitlab/shutdown.yml'
  - local: '.gitlab/logs.yml'
